# CustomStackSize Configuration
# Created by IIInitiationnn

# Item List
# Valid items can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Use the following format
# ITEM: STACKSIZE
