name: CustomStackSize
author: IIInitiationnn
main: customstacksize.main
version: 1.0
api-version: 1.16

commands:
  customstacksize:
    aliases: [css]
    description: Allows you to modify maximum stack sizes of items.

permissions:
  customstacksize.reload:
    default: op
  customstacksize.modify:
    default: op
  customstacksize.view:
    default: true